channels:
- conda-forge
dependencies:
- python=3.13.12
- pip<=26.0.1
- pip:
  - mlflow==3.9.0
  - cloudpickle==3.1.2
  - numpy==2.4.2
  - pandas==2.3.3
  - pydot==4.0.1
  - torch==2.10.0
  - torchvision==0.25.0
  - tqdm==4.67.3
name: mlflow-env
